### ISSUE TITLE
can i increase the sensibility of the method?

### ISSUE THREAD

**Issue by paumarc** [menzel/nopeak#5]
Hello

I am being using no peak script to discover motives from various chip seq samples, some of them have many coincident peaks, but i haven't found any coincident motive as i expected. on the other hand I only found two motives per sample, and i was expecting more.

The steps i did to discover motif were
1- run nopeak PROFILE
2- run nopeak LOGO
3- run plot_pwm. py

it is possible to change some parameters to increase the sensibility of the method?
thanks

**Comment by menzel** [comment]
Hello,

sry for the late reply, somehow I did not receive a notification.
How many reads are you using? Did you use the --strict parameter? 

If yes, omit it. If no you can make it even more sensibly by using --loose

This should change the filtering for profile shape in the LOGO step. But it also depends on the number of reads in the current setup.

If this does not help write me again, the parameters strict and loose translate to a smoothing cutoff in the Scoring.java file. You can adjust this further.

**Comment by menzel** [comment]
Also you can use the plot_pwm tool to plot the profile of any kmer. Maybe take a look a the profile (s) (you can use wildcards too) you expect to see and compare them to the expected shape from the paper

**Comment by paumarc** [comment]
thanks, i will try!
